name: CI Pipeline

on:
  pull_request:
  push:
    branches:
      - main
      - develop
  release:
    types: [published]

env:
  REGISTRY: docker.io
  IMAGE_PREFIX: zeahub

jobs:
  docker-init:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.set.outputs.tag }}
      build_needed: ${{ steps.check.outputs.build_needed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set files that trigger Docker build
        id: build_triggers
        run: |
          echo "files=Dockerfile poetry.lock pyproject.toml motd.sh" >> $GITHUB_OUTPUT

      - name: Compute Docker context hash
        id: docker_hash
        run: |
          HASH=$(cat Dockerfile poetry.lock pyproject.toml motd.sh | sha256sum | cut -c1-12)
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Set image tag
        id: set
        run: |
          echo "tag=${{ steps.docker_hash.outputs.hash }}" >> $GITHUB_OUTPUT

      - name: Check if Docker image exists
        id: image_exists
        run: |
          if docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/all-cpu:${{ steps.set.outputs.tag }} > /dev/null 2>&1; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if Docker build is needed
        id: check
        run: |
          if [[ "${{ steps.image_exists.outputs.found }}" == "true" ]]; then
            echo "build_needed=false" >> $GITHUB_OUTPUT
          else
            echo "build_needed=true" >> $GITHUB_OUTPUT
          fi

  build-full-image:
    needs: [docker-init, linter]
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space
        run : |
            echo "Disk space before cleanup:"
            df -h
            sudo rm -rf "/usr/local/share/boost"
            sudo rm -rf "$AGENT_TOOLSDIRECTORY"
            sudo rm -rf /opt/hostedtoolcache
            echo "Disk space after cleanup:"
            df -h

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push all-cpu Docker image
        if: needs.docker-init.outputs.build_needed == 'true'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          build-args: |
            INSTALL_JAX=cpu
            INSTALL_TORCH=cpu
            INSTALL_TF=cpu
            DEV=true
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/all-cpu:${{ needs.docker-init.outputs.docker_tag }}
          cache-from: type=registry,ref=${{ env.IMAGE_PREFIX }}/cache
          cache-to: type=registry,ref=${{ env.IMAGE_PREFIX }}/cache,mode=max

      - name: Pull all-cpu Docker image (no build)
        if: needs.docker-init.outputs.build_needed == 'false'
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/all-cpu:${{ needs.docker-init.outputs.docker_tag }}

  build-other-images:
    needs: [build-full-image, docker-init]
    runs-on: self-hosted
    strategy:
      max-parallel: 1
      matrix:
        backend: [all, jax, torch, tensorflow, numpy]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push CPU Docker image
        if: needs.docker-init.outputs.build_needed == 'true'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.backend }}-cpu:${{ needs.docker-init.outputs.docker_tag }}
          build-args: |
            INSTALL_JAX=${{ contains('all,jax', matrix.backend) && 'cpu' || 'false' }}
            INSTALL_TORCH=${{ contains('all,torch', matrix.backend) && 'cpu' || 'false' }}
            INSTALL_TF=${{ contains('all,tensorflow', matrix.backend) && 'cpu' || 'false' }}
          cache-from: type=registry,ref=${{ env.IMAGE_PREFIX }}/cache
          cache-to: type=registry,ref=${{ env.IMAGE_PREFIX }}/cache,mode=max

      - name: Pull CPU Docker image (no build)
        if: needs.docker-init.outputs.build_needed == 'false'
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.backend }}-cpu:${{ needs.docker-init.outputs.docker_tag }}

      - name: Build and push GPU Docker image
        if: needs.docker-init.outputs.build_needed == 'true' && matrix.backend != 'numpy'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.backend }}:${{ needs.docker-init.outputs.docker_tag }}
          build-args: |
            INSTALL_JAX=${{ (matrix.backend == 'all' || matrix.backend == 'jax') && 'gpu' || 'false' }}
            INSTALL_TORCH=${{ (matrix.backend == 'all' || matrix.backend == 'torch') && 'gpu' || 'false' }}
            INSTALL_TF=${{ (matrix.backend == 'all' || matrix.backend == 'tensorflow') && 'gpu' || 'false' }}
          cache-from: type=registry,ref=${{ env.IMAGE_PREFIX }}/cache
          cache-to: type=registry,ref=${{ env.IMAGE_PREFIX }}/cache,mode=max

      - name: Pull GPU Docker image (no build)
        if: needs.docker-init.outputs.build_needed == 'false' && matrix.backend != 'numpy'
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.backend }}:${{ needs.docker-init.outputs.docker_tag }}

  tests:
    if: github.event_name == 'pull_request'
    needs: [build-full-image, docker-init]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: git config --global safe.directory $GITHUB_WORKSPACE

      - name: Pull full Docker image
        run: |
          if [ -z "${{ needs.docker-init.outputs.docker_tag }}" ]; then
            echo "Image tag not set!" && exit 1
          fi
          docker pull ${{ env.IMAGE_PREFIX }}/all-cpu:${{ needs.docker-init.outputs.docker_tag }}

      - name: Run Pytest in container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/zea" \
            -w /zea \
            -u $(id -u):$(id -g) \
            -e HOME=/tmp \
            -e USER=$(id -un) \
            -e LOGNAME=$(id -un) \
            ${{ env.IMAGE_PREFIX }}/all-cpu:${{ needs.docker-init.outputs.docker_tag }} \
            sh -c "pip install -e . && pytest -p no:cacheprovider --cov --cov-branch --cov-report=xml  -m 'not heavy' ./tests"

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: tue-bmd/zea

      - name: Run heavy Pytest (allowed to fail)
        continue-on-error: true
        run: |
          docker run --rm \
          -v "${{ github.workspace }}:/zea" \
          -w /zea \
          -u $(id -u):$(id -g) \
          -e HOME=/tmp \
          -e USER=$(id -un) \
          -e LOGNAME=$(id -un) \
          ${{ env.IMAGE_PREFIX }}/all-cpu:${{ needs.docker-init.outputs.docker_tag }} \
          sh -c "pip install -e . && pytest -p no:cacheprovider -m 'heavy' ./tests"

  heavy-tests:
    if: github.event_name == 'pull_request'
    needs: [build-full-image, docker-init]
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: git config --global safe.directory $GITHUB_WORKSPACE

      - name: Pull full Docker image
        run: |
          if [ -z "${{ needs.docker-init.outputs.docker_tag }}" ]; then
            echo "Image tag not set!" && exit 1
          fi
          docker pull ${{ env.IMAGE_PREFIX }}/all-cpu:${{ needs.docker-init.outputs.docker_tag }}

      - name: Run heavy Pytest
        run: |
          docker run --rm \
          -v "${{ github.workspace }}:/zea" \
          -w /zea \
          -u $(id -u):$(id -g) \
          -e HOME=/tmp \
          -e USER=$(id -un) \
          -e LOGNAME=$(id -un) \
          ${{ env.IMAGE_PREFIX }}/all-cpu:${{ needs.docker-init.outputs.docker_tag }} \
          sh -c "pip install -e . && pytest -p no:cacheprovider -m 'heavy' ./tests"

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Ruff
        run: |
          pip install -U pip setuptools wheel
          pip install ruff
      - name: Run Linter
        run: ruff check --config pyproject.toml --verbose

      - name: Run Formatter
        run: ruff format --config pyproject.toml --check --verbose


  build-docs:
    needs: [build-full-image, docker-init]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: git config --global safe.directory $GITHUB_WORKSPACE

      - name: Pull full Docker image
        run: |
          if [ -z "${{ needs.docker-init.outputs.docker_tag }}" ]; then
            echo "Image tag not set!" && exit 1
          fi
          docker pull ${{ env.IMAGE_PREFIX }}/all-cpu:${{ needs.docker-init.outputs.docker_tag }}

      - name: Build documentation with Sphinx (fail on warnings)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/zea" \
            -w /zea/docs \
            -u $(id -u):$(id -g) \
            -e HOME=/tmp \
            -e USER=$(id -un) \
            -e LOGNAME=$(id -un) \
            ${{ env.IMAGE_PREFIX }}/all-cpu:${{ needs.docker-init.outputs.docker_tag }} \
            sh -c "\
              sudo apt-get update && \
              sudo apt-get install -y pandoc && \
              pip install -e ..[docs] && \
              export PATH=\"/tmp/.local/bin:\$PATH\" && \
              make docs-clean && \
              make docs-build SPHINXOPTS='-W --keep-going' \
            "
