name: Docs

on:
  workflow_run:
      # CI image will only build on main branch pushes or pull requests
      # thus so will this docs workflow
      workflows: ["Build CI Image"]
      types: ["completed"]

env:
  REGISTRY: docker.io
  IMAGE_PREFIX: zeahub

jobs:
  tag:
    uses: ./.github/workflows/set-tag.yaml

  build-docs:
    needs: [tag]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: git config --global safe.directory $GITHUB_WORKSPACE

      - name: Pull CI Docker image
        run: |
          if [ -z "${{ needs.tag.outputs.docker_tag }}" ]; then
            echo "Image tag not set!" && exit 1
          fi
          # Pull CI image that was built in build-image.yaml
          docker pull ${{ env.IMAGE_PREFIX }}/all-cpu:${{ needs.tag.outputs.docker_tag }}

      - name: Build documentation with Sphinx (fail on warnings)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/zea" \
            -w /zea/docs \
            -u $(id -u):$(id -g) \
            -e HOME=/tmp \
            -e USER=$(id -un) \
            -e LOGNAME=$(id -un) \
            ${{ env.IMAGE_PREFIX }}/all-cpu:${{ needs.tag.outputs.docker_tag }} \
            sh -c "\
              sudo apt-get update && \
              sudo apt-get install -y pandoc && \
              pip install -e ..[docs] && \
              export PATH=\"/tmp/.local/bin:\$PATH\" && \
              make docs-clean && \
              make docs-build SPHINXOPTS='-W --keep-going' \
            "
